# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python.  Multiline strings are treated as
# verbose regular expressions by Black.  Use [ ] to denote a significant space
# character.

[tool.black]
line-length = 119
target-version = ['py36', 'py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'
extend-exclude = '''
/(
    \.mypy_cache
  | \.tox
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 119

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true
warn_redundant_casts = true
no_implicit_optional = true
# Disable strict checking of Optional types and `None` values
no_strict_optional = true
allow_redefinition = true
#exclude = ['']
